==== IDE setup

- Open in your IDE the `producer` project (either via Maven or Gradle)
- We're assuming that we've taken over the PR. Example of how to achieve that in "real life" for a PR
that got submitted to via a branch called `the_pr` looks like this:

[source,bash]
----
git fetch origin
git checkout -b the_pr origin/the_pr
git merge master
----

- The idea of Spring Cloud Contract is about stub and contract validity. Right now we have a set of
 contracts defined but we haven't tested it against the producer side. Time to change that!

==== Setting up the Spring Cloud Contract plugin

- Spring Cloud Contract can generate tests from your contracts to ensure that your implementation's API
is compatible with the defined contract. Let's set up the project to start generating tests.
  * Spring Cloud Contract needs a base class that all of the generated tests will extend. Currently
  we support 3 different ways of defining a base class (you can read more about this in the
  Spring Cloud Contract documentation for https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_configure_plugin[Gradle]
  and https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#_configure_plugin_2[Maven])
    ** a single class for all tests
    ** convention based naming (takes 2 last package names and appends `Base`. Having a contract
    `src/test/resources/contracts/foo/bar/shouldDoSth.groovy` would create a test class called
    `BarTest` that would extend `FooBarBase` class.
    ** manual mapping (you can state that contracts matching certain regular expression will have to
    have a base class with fully qualified name equal to X)
  * In the following example we'll play with convention based naming
    ** For Maven under the plugin setup you have to set up the plugin configuration
    `<configuration><packageWithBaseClasses>com.example</packageWithBaseClasses></configuration>`
+
[source,xml,indent=0,subs="verbatim,attributes",role="primary"]
.Maven
----
<plugin>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-contract-maven-plugin</artifactId>
    <version>${spring-cloud-contract.version}</version>
    <extensions>true</extensions>
    <configuration>
        <packageWithBaseClasses>com.example</packageWithBaseClasses>
    </configuration>
</plugin>
----
+
[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Gradle
----
contracts {
    packageWithBaseClasses = 'com.example'
}
----
    ** In both cases passing of that value tells the plugin that a given base class is available under
    the `com.example` package