version: '2'

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  broker_app:
    image: dius/pact-broker
    ports:
      - "8085:80"
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres

#  nginx:
#    image: nginx:alpine
#    links:
#      - broker_app:broker
#    volumes:
#    - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#    - ./ssl:/etc/nginx/ssl
#    ports:
#    - "8443:443"
