:toc: left
:toclevels: 8
:nofooter:
:images_folder: images

= Spring Cloud Contract Workshops

This documentation will allow you to go through Spring Cloud Contract Workshops by completing
a series of tasks that will teach you the basic and more advanced concept behind Consumer Driven Contracts
and Spring Cloud Contract as such.

== Setup

The repository mostly consists of pairs of `producer` and `consumer` applications that show
different use cases of Spring Cloud Contract. The initial state of the repository
is such that all the examples are working and the tests are passing. In order for you to prepare
the repository so it has only the basic pieces of code set up execute this Gradle command

[source,groovy]
----
$ git clone https://github.com/spring-cloud-samples/spring-cloud-contract-samples
$ cd spring-cloud-contract-samples
$ ./gradlew prepareForWorkshops
----

This command will remove most of the code / contracts / project setup so that you can start
with the workshops.

TIP: Whenever your lost - don't worry. It's enough to check what's there in the `master` branch
where all of the examples are ready and working.

TIP: The tasks are set in a form of a cookbook. You can pick any task you want -
you don't have to go through them one by one.

IMPORTANT: You'll also need to have Maven installed. Check out https://maven.apache.org/download.cgi[
the website on how to download and install Maven]

== Generating the documentation

To generate the whole documentation it's enough to call the Gradle task:

[source,groovy]
----
$ git clone https://github.com/spring-cloud-samples/spring-cloud-contract-samples
$ cd spring-cloud-contract-samples
$ ./gradlew generateDocumentation
----

== Resources

//TODO: Add the links / slides

=== Adib Saikali's introduction to Consumer Driven Contracts

++++
<iframe src="https://docs.google.com/presentation/d/1-_2_Ok-inGA75cr8DwTyeMuhkEGSuaZ4M8FKGV6W5hU/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
++++

{nbsp}
{nbsp}

video::iyNzYOcuU4I[youtube,start=538,width=960,height=569]

{nbsp}
{nbsp}

=== Introduction to Spring Cloud Contract

++++
<iframe src="https://docs.google.com/presentation/d/1fB63Pm4nSItw9nJ9zyhAIw2KAZ4mazZZHHGAW6e0Srg/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
++++

== Tasks

- link:tutorials/contracts_on_the_producer_side.html[Contracts on the producer side]
  * simple DSL examples for HTTP & Messaging
  * base classes picked by convention
  * generating documentation from contracts
- link:tutorials/contracts_external.html[Contracts that lay in an external repository]
  * simple DSL examples for HTTP & Messaging
  * base classes picked by mappings
  * generating documentation from contracts
- link:tutorials/rest_docs.html[Spring Cloud Contract with Rest Docs]
  * generating stubs using Rest Docs
  * generating contracts using Rest Docs
  * reading stubs from classpath via Spring Cloud Contract WireMock
  * reading stubs from classpath via Stub Runner
- Extras
  * more sophisticated DSL manipulations (regexs, code execution, referencing request from response)
  * working with stub and test matchers
  * link:tutorials/contracts_representing_scenarios.html[contracts representing scenarios (stateful stubs)]
  * creating a library with common code shareable between teams
  * link:tutorials/stubbing_out_service_discovery.html[stubbing out service discovery]
  * stubs per consumer feature
  * using JUnit rule
- Using stubs with Stub Runner Boot


