// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beer.proto

package com.example;

public interface PersonToCheckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beer.PersonToCheck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
