// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beer.proto

package com.example;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beer.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.beer.Response.BeerCheckStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.beer.Response.BeerCheckStatus status = 1;</code>
   * @return The status.
   */
  com.example.Response.BeerCheckStatus getStatus();
}
